### ISSUE TITLE
Core とは何か？を議論したい

### ISSUE THREAD

**Issue by lambdalisue** [vim-vital/vital-core#1]
Core の立ち位置として以下のようなものを提唱します。

1. Vim/Neovim どちらでも動くもの（Vim 8.0, Neovim 0.2.0 が最低ライン）
    - 全部 CI でテストする
    - Linux は docker
    - Mac は Travis
    - Windows は AppVeyor
2. ドキュメント・テストが充実しているモジュールに限定
3. 機能がアトム的で、特定の機能に対して、そのモジュールが必須に近い存在のもの
    - `Async.Promise`
4. 現在のモジュールから必須に近いもののみを抽出したもの
    - `Data.String` の一部
5. Vim/Neovim の差異を吸収するためには必須なもの
    - `Whisky.System.Job`

上記に当てはまらないものは

- vital-mantle  ドキュメント・テストが充実しているモレキュラーレベルのモジュール群
- vital-crust   実験的・限定的なモジュール群

として別議論。

どうでしょう？これで良さそうなら「何を core として入れるか？」の議論を別 issue で行いたいです

**Comment by ujihisa** [comment]
:+1:
let's do that!

**Comment by lambdalisue** [comment]
ずっとOpenで置いておいても無意味なので、とりあえず現状は上記で確定したとします。異論等あれば、別枠ではissueにしましょう。

**Comment by ujihisa** [comment]
:clap:
